name: CI/CD to Databricks Prod Workspace

on:
  push:
    branches:
      - main

jobs:
  deploy-to-databricks:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Databricks CLI
      run: |
        pip install databricks-cli

    - name: Configure Databricks CLI
      run: |
        mkdir -p ~/.databricks
        echo "[DEFAULT]" > ~/.databricks/config
        echo "host = ${{ secrets.DATABRICKS_HOST }}" >> ~/.databricks/config
        echo "token = ${{ secrets.DATABRICKS_TOKEN }}" >> ~/.databricks/config

    - name: Upload notebooks to Databricks workspace
      run: |
        find . -name "*.py" -or -name "*.ipynb" | while read file; do
          dest_path="/Workspace/Users/nikesh.kaza@accenture.com/mlops_main/${file#./}"
          if [[ "$file" == *.py ]]; then
            lang="PYTHON"
          elif [[ "$file" == *.ipynb ]]; then
            lang="PYTHON"  # or "NOTEBOOK" — both usually work, depending on your setup
          else
            echo "Skipping $file (unknown type)"
            continue
          fi
          echo "Uploading $file to $dest_path as $lang"
          databricks workspace import "$file" "$dest_path" --language $lang --overwrite
        done

